# Generated by Django 3.2.3 on 2021-07-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Yet to start', 'Yet to start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'stype': '3'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
    ]
