# Generated by Django 3.2.3 on 2021-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staff_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100, null=True),
        ),
    ]
