# Generated by Django 3.2.3 on 2021-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_batch_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='passcode',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
