# Generated by Django 3.2.3 on 2021-07-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_batch_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
            ],
        ),
    ]
