# Generated by Django 3.2.3 on 2021-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_batchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursedata',
            name='payment',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=10),
        ),
    ]
