# Generated by Django 3.2.3 on 2021-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_studentcoursedata_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdata',
            name='datecreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
