# Generated by Django 3.2.3 on 2021-07-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_batchdata_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=400, null=True)),
                ('message', models.CharField(blank=True, max_length=1500, null=True)),
                ('datetime', models.DateField(blank=True, default=datetime.datetime(2021, 7, 19, 23, 44, 13, 277658), null=True)),
            ],
        ),
    ]
