# Generated by Django 3.2.3 on 2021-07-21 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210720_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 7, 26, 34, 590108), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='query',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(blank=True, choices=[('Not replied', 'Not replied'), ('Replied', 'Replied')], default='Not replied', max_length=100),
        ),
    ]
