# Generated by Django 3.2.3 on 2021-07-21 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210721_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 7, 38, 19, 289950), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='receiver',
            field=models.ForeignKey(blank=True, limit_choices_to={'stype': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.staff'),
        ),
    ]
