# Generated by Django 3.2.3 on 2021-07-21 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210721_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 7, 40, 14, 426185), null=True),
        ),
    ]
