# Generated by Django 3.2.3 on 2021-07-21 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210721_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 7, 58, 39, 918238), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='message',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='subject',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
