# Generated by Django 3.2.3 on 2021-07-21 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210721_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 7, 59, 32, 266840), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'stype': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.staff'),
        ),
    ]
