# Generated by Django 3.2.3 on 2021-07-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210721_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 14, 37, 5, 543552), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 14, 37, 5, 542556), null=True),
        ),
    ]
