# Generated by Django 3.2.3 on 2021-07-21 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0036_auto_20210721_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='query',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 21, 28, 29, 654611), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 21, 28, 29, 654611), null=True),
        ),
    ]
