# Generated by Django 3.2.3 on 2021-07-21 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210721_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 22, 12, 27, 792526), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 22, 12, 27, 790531), null=True),
        ),
    ]
