# Generated by Django 3.2.3 on 2021-07-21 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210721_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 22, 42, 20, 266843), null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 21, 22, 42, 20, 265845), null=True),
        ),
    ]
