# Generated by Django 3.2.5 on 2021-07-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210721_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 22, 17, 55, 41, 659621), null=True),
        ),
    ]
