# Generated by Django 3.2.5 on 2021-07-22 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210722_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 23, 0, 46, 39, 532197), null=True),
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, null=True)),
                ('message', models.TextField(max_length=1500, null=True)),
                ('ss1', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('ss2', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('ss3', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('reply', models.TextField(blank=True, max_length=1500, null=True)),
                ('datetime', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Not replied', 'Not replied'), ('Replied', 'Replied')], default='Not replied', max_length=100)),
                ('receiver', models.ForeignKey(limit_choices_to={'stype': '3'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='accounts.staff')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std', to='accounts.student')),
            ],
        ),
    ]
