# Generated by Django 3.2.5 on 2021-07-26 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210724_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Weekday'), ('2', 'Weekend')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, choices=[('Yet to start', 'Yet to start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Yet to start', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'stype': '3'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 18, 9, 11, 688955), null=True),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='batch',
            field=models.ForeignKey(limit_choices_to={models.Q(('status', 'Completed'), _negated=True)}, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='accounts.batch'),
        ),
    ]
