# Generated by Django 3.2.5 on 2021-07-26 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210726_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 18, 12, 7, 69918), null=True),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='batch',
            field=models.ForeignKey(limit_choices_to=models.Q(('status', 'Ongoing'), ('status', 'Yet to start'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='accounts.batch'),
        ),
    ]
