# Generated by Django 3.2.5 on 2021-07-26 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210726_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 18, 48, 51, 461201), null=True),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='batch',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status', 'Ongoing'), ('status', 'Yet to start'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='accounts.batch'),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='payment',
            field=models.CharField(blank=True, choices=[('Full', 'Full'), ('Half', 'Half'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.student'),
        ),
    ]
