# Generated by Django 3.2.5 on 2021-07-26 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210726_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Pipeline', 'In Pipeline'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Not Interested', 'Not Interested')], default='New', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 21, 1, 4, 581161), null=True),
        ),
    ]
