# Generated by Django 3.2.5 on 2021-07-26 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210726_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='generator',
            field=models.ForeignKey(blank=True, limit_choices_to={'stype': '2'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 21, 31, 15, 805149), null=True),
        ),
    ]
