# Generated by Django 3.2.5 on 2021-07-27 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20210726_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 27, 9, 31, 11, 429478), null=True),
        ),
    ]
