# Generated by Django 3.2.5 on 2021-07-29 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210729_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 29, 19, 3, 28, 839208), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='student.jpg', null=True, upload_to=''),
        ),
    ]
