# Generated by Django 3.2.5 on 2021-07-31 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210729_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 31, 10, 46, 31, 293972), null=True),
        ),
        migrations.AlterField(
            model_name='studentcoursedata',
            name='optional',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('Yet to start', 'Yet to start'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Yet to start', max_length=100),
        ),
    ]
