# Generated by Django 3.2.5 on 2021-07-31 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20210731_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 31, 17, 26, 52, 948365), null=True),
        ),
    ]
