# Generated by Django 3.2.5 on 2021-08-01 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20210731_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 1, 13, 6, 26, 301300), null=True),
        ),
        migrations.CreateModel(
            name='StudentProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('submitted_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Waiting for approval', 'Waiting for approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Waiting for approval', max_length=20, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_batch', to='accounts.batch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='accounts.student')),
            ],
        ),
    ]
