# Generated by Django 3.2.5 on 2021-08-01 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20210801_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 1, 16, 55, 22, 351956), null=True),
        ),
        migrations.AlterField(
            model_name='studentprojectdata',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting for approval', 'Waiting for approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Waiting for approval', max_length=20, null=True),
        ),
    ]
