# Generated by Django 3.2.5 on 2021-08-03 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20210801_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprojectdata',
            name='certificate',
        ),
        migrations.AddField(
            model_name='studentprojectdata',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 3, 19, 9, 44, 783524), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-circle-solid.jpg', null=True, upload_to=''),
        ),
    ]
