# Generated by Django 3.2.5 on 2021-08-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20210803_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 5, 23, 20, 13, 260500), null=True),
        ),
    ]
